In [ ]:
import pandas as pd
import numpy as np
import re

from collections import Counter, defaultdict
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
DEV_PATH  = "../data/raw/development.csv"
SUB_PATH  = "submissionnoparese2.csv"
EVAL_PATH = "../data/raw/evaluation.csv"

MIN_RULE_SUPPORT = 30
MIN_RULE_PURITY  = 0.95
RULE_PRIORITY    = "best_purity_then_freq"

C_VALUE = 1.5
df_dev  = pd.read_csv(DEV_PATH)
df_eval = pd.read_csv(EVAL_PATH)

for df in (df_dev, df_eval):
    df["article"] = df["article"].fillna("").astype(str)
    df["title"]   = df["title"].fillna("").astype(str)
    df["source"]  = df["source"].fillna("").astype(str)
def build_model_text(df):
    return (df["title"] + " " + df["article"]).str.lower()

df_dev["text"]  = build_model_text(df_dev)
df_eval["text"] = build_model_text(df_eval)
def add_numeric(df):
    df["n_tokens"]    = df["article"].str.split().str.len()
    df["title_len"]   = df["title"].str.len()
    df["article_len"] = df["article"].str.len()
    df["title_ratio"] = df["title_len"] / (df["article_len"] + 1)
    return df

df_dev  = add_numeric(df_dev)
df_eval = add_numeric(df_eval)

NUM_COLS = ["n_tokens", "title_len", "article_len", "title_ratio"]

for df in (df_dev, df_eval):
    df[NUM_COLS] = df[NUM_COLS].replace([np.inf, -np.inf], 0).fillna(0)

FEATURES = ["source", "text"] + NUM_COLS

X_dev  = df_dev[FEATURES]
y_dev  = df_dev["label"].astype(int)
X_eval = df_eval[FEATURES]


def mine_pure_rules(texts, labels):
    counts = defaultdict(lambda: Counter())



    rule_token_to_class = {}
    rule_meta = {}

    for tok, c in counts.items():
        total = sum(c.values())
        if total < MIN_RULE_SUPPORT:
            continue

        best_class, best_freq = c.most_common(1)[0]
        purity = best_freq / total

        if purity >= MIN_RULE_PURITY:
            rule_token_to_class[tok] = int(best_class)
            rule_meta[tok] = (purity, total)

    return rule_token_to_class, rule_meta
def apply_rules(texts, rule_token_to_class, rule_meta):
    rule_pred = np.full(len(texts), -1, dtype=int)

    for i, txt in enumerate(texts):
        toks = set(tokenize_for_rules(txt))
        hits = [t for t in toks if t in rule_token_to_class]
        if not hits:
            continue

        hits.sort(
            key=lambda t: (rule_meta[t][0], rule_meta[t][1]),
            reverse=True
        )

        rule_pred[i] = rule_token_to_class[hits[0]]

    return rule_pred


def make_model():
    pre = ColumnTransformer(
        transformers=[
            ("src", OneHotEncoder(handle_unknown="ignore"), ["source"]),
            ("w_tfidf", TfidfVectorizer(
                analyzer="word",
                ngram_range=(1, 2),
                min_df=3,
                max_df=0.9,
                sublinear_tf=True,
                max_features=250_000
            ), "text"),
            ("c_tfidf", TfidfVectorizer(
                analyzer="char_wb",
                ngram_range=(3, 5),
                min_df=3,
                max_df=0.9,
                sublinear_tf=True,
                max_features=300_000
            ), "text"),
            ("num", StandardScaler(), NUM_COLS),
        ],
        remainder="drop",
        n_jobs=-1
    )

    clf = LogisticRegression(
        C=C_VALUE,
        class_weight="balanced",
        max_iter=2000,
        n_jobs=-1
    )

    return Pipeline([
        ("pre", pre),
        ("clf", clf),
    ])
model = make_model()
model.fit(X_dev, y_dev)

rule_token_to_class, rule_meta = mine_pure_rules(
    df_dev["article"],
    y_dev
)

print("Rules mined:", len(rule_token_to_class))

model_pred = model.predict(X_eval)

rule_pred = apply_rules(
    df_eval["article"],
    rule_token_to_class,
    rule_meta
)

final_pred = model_pred.copy()
mask = rule_pred != -1
final_pred[mask] = rule_pred[mask]

print(f"Rule coverage on eval: {mask.mean():.3f}")


submission = pd.DataFrame({
    "Id": df_eval["Id"].astype(int),
    "Predicted": final_pred.astype(int)
})

submission.to_csv(SUB_PATH, index=False)
print("Saved:", SUB_PATH)

Rules mined: 0
Rule coverage on eval: 0.000
Saved: submissionnoparese2.csv

In [12]:
SUB_PATH  = "submissionnoparese3.csv"
submission.to_csv(SUB_PATH, index=False)
print("Saved:", SUB_PATH)

Saved: submissionnoparese3.csv

In [13]:
submission.head()

   Id  Predicted
0   0          5
1   1          2
2   2          5
3   3          1
4   4          5

In [2]:
# ============================================================
# BASELINE — SINGLE-STAGE LINEAR MODEL (NO TWO-STAGE)
# - Regex HTML / URL friendly
# - Timestamp DROPPED
# - Train on FULL DEVELOPMENT
# - Predict on EVAL
# - Kaggle submission ready
# ============================================================

import pandas as pd
import numpy as np
import re

from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# ============================================================
# PATHS (KAGGLE)
# ============================================================

DEV_PATH  = "../data/raw/development.csv"
SUB_PATH  = "baseline.csv"
EVAL_PATH = "../data/raw/evaluation.csv"

# ============================================================
# LOAD DATA
# ============================================================
df_dev  = pd.read_csv(DEV_PATH)
df_eval = pd.read_csv(EVAL_PATH)

# ---- DROP TIMESTAMP COMPLETELY ----
df_dev  = df_dev.drop(columns=["timestamp"], errors="ignore")
df_eval = df_eval.drop(columns=["timestamp"], errors="ignore")

# ============================================================
# BASIC FIXES
# ============================================================
for df in (df_dev, df_eval):
    df["article"] = df["article"].fillna("").astype(str)
    df["title"]   = df["title"].fillna("").astype(str)
    df["source"]  = df["source"].fillna("").astype(str)

# ============================================================
# TEXT (JOINED)
# ============================================================
def build_text(df):
    return (df["title"] + " " + df["article"]).str.lower()

df_dev["text"]  = build_text(df_dev)
df_eval["text"] = build_text(df_eval)

# ============================================================
# NUMERIC FEATURES
# ============================================================
def add_numeric(df):
    df["n_tokens"]    = df["article"].str.split().str.len()
    df["title_len"]   = df["title"].str.len()
    df["article_len"] = df["article"].str.len()
    df["title_ratio"] = df["title_len"] / (df["article_len"] + 1)
    return df

df_dev  = add_numeric(df_dev)
df_eval = add_numeric(df_eval)

NUM_COLS = ["n_tokens", "title_len", "article_len", "title_ratio"]

for df in (df_dev, df_eval):
    df[NUM_COLS] = df[NUM_COLS].replace([np.inf, -np.inf], 0).fillna(0)

# ============================================================
# FEATURES
# ============================================================
FEATURES = ["source", "text"] + NUM_COLS

X_dev  = df_dev[FEATURES]
y_dev  = df_dev["label"].astype(int)
X_eval = df_eval[FEATURES]

# ============================================================
# MODEL (NO RULES)
# ============================================================
pre = ColumnTransformer(
    transformers=[
        ("src", OneHotEncoder(handle_unknown="ignore"), ["source"]),

        ("w_tfidf", TfidfVectorizer(
            analyzer="word",
            ngram_range=(1, 2),
            min_df=3,
            max_df=0.9,
            sublinear_tf=True,
            max_features=250_000
        ), "text"),

        ("c_tfidf", TfidfVectorizer(
            analyzer="char_wb",
            ngram_range=(3, 5),
            min_df=3,
            max_df=0.9,
            sublinear_tf=True,
            max_features=300_000
        ), "text"),

        ("num", StandardScaler(), NUM_COLS),
    ],
    remainder="drop",
    n_jobs=-1
)

model = Pipeline([
    ("pre", pre),
    ("clf", LogisticRegression(
        C=1.5,
        class_weight="balanced",
        max_iter=2000,
        n_jobs=-1
    ))
])

# ============================================================
# TRAIN ON FULL DEVELOPMENT
# ============================================================
print("Training baseline model on full development...")
model.fit(X_dev, y_dev)

# ============================================================
# PREDICT ON EVAL
# ============================================================
print("Predicting on evaluation...")
final_pred = model.predict(X_eval)

# ============================================================
# SUBMISSION
# ============================================================
submission = pd.DataFrame({
    "Id": df_eval["Id"].astype(int),
    "Predicted": final_pred.astype(int)
})

submission.to_csv(SUB_PATH, index=False)
print("Submission saved to:", SUB_PATH)

Training baseline model on full development...
Predicting on evaluation...
Submission saved to: baseline.csv

In [3]:
row_by_id = df_dev[df_dev["Id"] == 310]
row_by_idx = df_dev.iloc[310]

print("=== BY Id ===")
print(row_by_id[["Id", "source", "title", "article"]])

print("\n=== BY iloc[310] ===")
print(row_by_idx[["Id", "source", "title", "article"]])

=== BY Id ===
      Id source                              title  \
310  310    BBC  Jaguar negotiates Â£534m Ford aid

                                               article
310  Ford will inject Â£534m into Jaguar, after the...

=== BY iloc[310] ===
Id                                                       310
source                                                   BBC
title                      Jaguar negotiates Â£534m Ford aid
article    Ford will inject Â£534m into Jaguar, after the...
Name: 310, dtype: object

In [4]:
import re 
def has_broken_currency(text):
    return bool(re.search(r"Â[$£€¥]", text))

df_dev["broken_currency"] = df_dev["article"].apply(has_broken_currency)
df_dev["broken_currency"].mean()

np.float64(0.004325162193582259)

In [5]:
df_dev[df_dev["broken_currency"]].groupby("label").size().sort_values(ascending=False)

label
5    102
0     96
1     70
3     36
2     28
4     12
6      2
dtype: int64

In [6]:
def contains_currency_symbol(text):
    return any(sym in text for sym in ["£", "$", "€", "¥"])

df_dev["has_currency"] = df_dev["article"].apply(contains_currency_symbol)

df_dev.groupby("label")["has_currency"].mean().sort_values(ascending=False)

label
1    0.139686
2    0.058507
3    0.039591
5    0.035777
4    0.027059
0    0.024467
6    0.022566
Name: has_currency, dtype: float64

In [7]:
import re

CURRENCY_PATTERN = re.compile(
    r"(Â?[£$€¥])|\b(dollar|dollars|euro|euros|pound|pounds|yen)\b",
    flags=re.IGNORECASE
)

import re

CURRENCY_PATTERN = re.compile(
    r"(Â?[£$€¥])|\b(dollar|dollars|euro|euros|pound|pounds|yen)\b",
    flags=re.IGNORECASE
)
df_currency = df_dev[
    df_dev["article"].apply(lambda x: bool(CURRENCY_PATTERN.search(x)))
].copy()

print("Currency dataset size:", len(df_currency))
print("Percentage of dev:", len(df_currency) / len(df_dev))

df_currency["label"].value_counts(normalize=True).sort_index()
df_currency["label"].value_counts(normalize=True).sort_index()

Currency dataset size: 4995
Percentage of dev: 0.06243984149405603

label
0    0.192392
1    0.371371
2    0.152352
3    0.097497
4    0.054454
5    0.110310
6    0.021622
Name: proportion, dtype: float64

In [8]:
df_currency["label"].value_counts(normalize=True).sort_index()

label
0    0.192392
1    0.371371
2    0.152352
3    0.097497
4    0.054454
5    0.110310
6    0.021622
Name: proportion, dtype: float64

In [10]:
df_dev["label"].value_counts(normalize=True).sort_index()

label
0    0.294286
1    0.132355
2    0.139518
3    0.124717
4    0.107179
5    0.163169
6    0.038776
Name: proportion, dtype: float64

In [11]:
from collections import Counter

label_counts = Counter(df_currency["label"])
label_counts
total = sum(label_counts.values())
{lbl: cnt / total for lbl, cnt in label_counts.items()}

{0: 0.1923923923923924,
 5: 0.11031031031031031,
 3: 0.0974974974974975,
 2: 0.15235235235235237,
 1: 0.3713713713713714,
 4: 0.05445445445445445,
 6: 0.021621621621621623}

In [16]:
# ============================================================
# BASELINE LINEAR MODEL — CURRENCY FIX + REGEX (NO RULES)
# ============================================================

import pandas as pd
import numpy as np
import re

from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# =========================
# CONFIG
# =========================

DEV_PATH  = "../data/raw/development.csv"
SUB_PATH  = "submission_baseline_currency.csv"
EVAL_PATH = "../data/raw/evaluation.csv"

C_VALUE = 1.5

# =========================
# LOAD
# =========================
df_dev  = pd.read_csv(DEV_PATH)
df_eval = pd.read_csv(EVAL_PATH)

# =========================
# BASIC FIXES
# =========================
for df in (df_dev, df_eval):
    df["article"] = df["article"].fillna("").astype(str)
    df["title"]   = df["title"].fillna("").astype(str)
    df["source"]  = df["source"].fillna("").astype(str)

# =========================
# TEXT CLEANING (MINIMAL & SAFE)
# =========================
def fix_encoding(text):
    try:
        return text.encode("latin1").decode("utf-8")
    except:
        return text

def normalize_currency(text):
    return re.sub(
        r"[£$€¥]\s*\d+(\.\d+)?\s*(m|bn|million|billion)?",
        "CURRENCY_AMOUNT",
        text,
        flags=re.I
    )

def clean_text(text):
    text = fix_encoding(text)
    text = normalize_currency(text)
    return text.lower()

# =========================
# BUILD TEXT
# =========================
for df in (df_dev, df_eval):
    df["text"] = (df["title"] + " " + df["article"]).apply(clean_text)

# =========================
# NUMERIC FEATURES
# =========================
def add_numeric(df):
    df["n_tokens"]    = df["article"].str.split().str.len()
    df["title_len"]   = df["title"].str.len()
    df["article_len"] = df["article"].str.len()
    df["title_ratio"] = df["title_len"] / (df["article_len"] + 1)
    return df

df_dev  = add_numeric(df_dev)
df_eval = add_numeric(df_eval)

NUM_COLS = ["n_tokens", "title_len", "article_len", "title_ratio"]

for df in (df_dev, df_eval):
    df[NUM_COLS] = df[NUM_COLS].replace([np.inf, -np.inf], 0).fillna(0)

# =========================
# FEATURES
# =========================
FEATURES = ["source", "text"] + NUM_COLS

X_dev  = df_dev[FEATURES]
y_dev  = df_dev["label"].astype(int)
X_eval = df_eval[FEATURES]

# =========================
# MODEL
# =========================
pre = ColumnTransformer(
    transformers=[
        ("src", OneHotEncoder(handle_unknown="ignore"), ["source"]),
        ("w", TfidfVectorizer(
            analyzer="word",
            ngram_range=(1,2),
            min_df=3,
            max_df=0.9,
            sublinear_tf=True,
            max_features=250_000,
            token_pattern=r"[a-z0-9_:/\.]+"
        ), "text"),
        ("c", TfidfVectorizer(
            analyzer="char_wb",
            ngram_range=(3,5),
            min_df=3,
            max_df=0.9,
            sublinear_tf=True,
            max_features=300_000
        ), "text"),
        ("n", StandardScaler(), NUM_COLS),
    ],
    remainder="drop",
    n_jobs=-1
)

model = Pipeline([
    ("pre", pre),
    ("clf", LogisticRegression(
        C=C_VALUE,
        class_weight="balanced",
        max_iter=2000,
        n_jobs=-1
    ))
])

# =========================
# TRAIN
# =========================
print("Training baseline model...")
model.fit(X_dev, y_dev)

# =========================
# PREDICT
# =========================
pred = model.predict(X_eval)

# =========================
# SUBMISSION
# =========================
submission = pd.DataFrame({
    "Id": df_eval["Id"].astype(int),
    "Predicted": pred.astype(int)
})

submission.to_csv(SUB_PATH, index=False)
print("Saved:", SUB_PATH)

Training baseline model...
Saved: submission_baseline_currency.csv

In [21]:
df = pd.read_csv(DEV_PATH)
df["article"] = df["article"].fillna("").astype(str)
df["title"]   = df["title"].fillna("").astype(str)

# testo completo (come nel modello baseline)
df["text"] = (df["title"] + " " + df["article"]).str.lower()

In [22]:
# regex: tutto ciò che NON è lettera, spazio o backslash
non_alpha_regex = re.compile(r"[^a-zA-Z\\ ]")

def count_non_alpha(text):
	return len(non_alpha_regex.findall(text))

df["non_alpha_chars"] = df["text"].apply(count_non_alpha)
df["text_len"] = df["text"].str.len()

# normalizziamo anche per lunghezza
df["non_alpha_ratio"] = df["non_alpha_chars"] / (df["text_len"] + 1)

agg = df.groupby("label").agg(
	mean_non_alpha=("non_alpha_chars", "mean"),
	median_non_alpha=("non_alpha_chars", "median"),
	mean_ratio=("non_alpha_ratio", "mean"),
	median_ratio=("non_alpha_ratio", "median"),
	count=("label", "count")
)

agg

df.groupby("label")["non_alpha_ratio"].describe()

,count,mean,std,min,25%,50%,75%,max
label,,,,,,,,
0,23542.0,0.064976,0.065837,0.0,0.023585,0.037190,0.067164,0.386861
1,10588.0,0.066832,0.073914,0.0,0.024820,0.041971,0.071675,0.433198
2,11161.0,0.080503,0.078155,0.0,0.028409,0.048148,0.096774,0.473373
3,9977.0,0.065736,0.060439,0.0,0.028169,0.046218,0.073930,0.326007
4,8574.0,0.067739,0.060060,0.0,0.030120,0.047393,0.076495,0.349206
5,13053.0,0.061565,0.071830,0.0,0.021583,0.035714,0.061372,0.379310
6,3102.0,0.045616,0.042375,0.0,0.022035,0.033988,0.052448,0.338816

In [23]:
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

X = df[["non_alpha_ratio"]]
y = df["label"]

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = []

for tr, te in skf.split(X, y):
	clf = LogisticRegression(max_iter=1000, class_weight="balanced")
	clf.fit(X.iloc[tr], y.iloc[tr])
	pred = clf.predict(X.iloc[te])
	scores.append(f1_score(y.iloc[te], pred, average="macro"))

np.mean(scores)

np.float64(0.07399728425851884)

In [ ]:
import re

URL_REGEX = re.compile(
    r"(http?://[^\s\"\'<>]+)",
    flags=re.IGNORECASE
)

def extract_urls(text):
    return URL_REGEX.findall(text)

df_dev["urls"] = df_dev["article"].apply(extract_urls)
df_dev["n_urls"] = df_dev["urls"].str.len()
df_dev.groupby("label")["n_urls"].describe()

         count      mean       std  min  25%  50%  75%   max
label
0      23542.0  0.448602  1.220120  0.0  0.0  0.0  0.0  28.0
1      10588.0  0.342180  1.023816  0.0  0.0  0.0  0.0  12.0
2      11161.0  1.216647  3.133501  0.0  0.0  0.0  0.0  56.0
3       9977.0  0.395109  2.026352  0.0  0.0  0.0  0.0  65.0
4       8574.0  0.252508  0.747508  0.0  0.0  0.0  0.0   9.0
5      13053.0  0.438980  1.859834  0.0  0.0  0.0  0.0  13.0
6       3102.0  0.153449  0.804886  0.0  0.0  0.0  0.0   9.0

In [35]:
import re

URL_REGEX = re.compile(
    r"(https?://[^\s\"\'<>]+)",
    flags=re.IGNORECASE
)

def extract_urls(text):
    return URL_REGEX.findall(text)

df_dev["urls"] = df_dev["article"].apply(extract_urls)
df_dev["n_urls"] = df_dev["urls"].str.len()
df_dev.groupby("label")["n_urls"].describe()

         count      mean       std  min  25%  50%  75%   max
label
0      23542.0  0.448602  1.220120  0.0  0.0  0.0  0.0  28.0
1      10588.0  0.342180  1.023816  0.0  0.0  0.0  0.0  12.0
2      11161.0  1.218170  3.134639  0.0  0.0  0.0  0.0  56.0
3       9977.0  0.395109  2.026352  0.0  0.0  0.0  0.0  65.0
4       8574.0  0.252508  0.747508  0.0  0.0  0.0  0.0   9.0
5      13053.0  0.438980  1.859834  0.0  0.0  0.0  0.0  13.0
6       3102.0  0.153449  0.804886  0.0  0.0  0.0  0.0   9.0

In [36]:
import re

URL_REGEX = re.compile(
    r"(https?://[^\s\"\'<>]+)",
    flags=re.IGNORECASE
)

def extract_urls(text):
    return URL_REGEX.findall(text)

df_dev["urls"] = df_dev["article"].apply(extract_urls)
df_dev["n_urls"] = df_dev["urls"].str.len()
df_dev.groupby("label")["n_urls"].describe()

         count      mean       std  min  25%  50%  75%   max
label
0      23542.0  0.448602  1.220120  0.0  0.0  0.0  0.0  28.0
1      10588.0  0.342180  1.023816  0.0  0.0  0.0  0.0  12.0
2      11161.0  1.218170  3.134639  0.0  0.0  0.0  0.0  56.0
3       9977.0  0.395109  2.026352  0.0  0.0  0.0  0.0  65.0
4       8574.0  0.252508  0.747508  0.0  0.0  0.0  0.0   9.0
5      13053.0  0.438980  1.859834  0.0  0.0  0.0  0.0  13.0
6       3102.0  0.153449  0.804886  0.0  0.0  0.0  0.0   9.0

In [28]:
def extract_domain(url):
    m = re.search(r"http?://([^/]+)/?", url)
    return m.group(1).lower() if m else None

df_dev["domains"] = df_dev["urls"].apply(
    lambda urls: [extract_domain(u) for u in urls]
)
dom_df = df_dev[["label", "domains"]].explode("domains")
dom_df = dom_df.dropna()

In [29]:
from collections import Counter

domain_stats = {}

for dom, g in dom_df.groupby("domains"):
    cnt = Counter(g["label"])
    total = sum(cnt.values())
    best_label, best_freq = cnt.most_common(1)[0]
    purity = best_freq / total
    if total >= 30 and purity >= 0.9:
        domain_stats[dom] = (best_label, purity, total)

len(domain_stats)

13

In [37]:
def extract_domain(url):
    m = re.search(r"https?://([^/]+)/?", url)
    return m.group(1).lower() if m else None

df_dev["domains"] = df_dev["urls"].apply(
    lambda urls: [extract_domain(u) for u in urls]
)
dom_df = df_dev[["label", "domains"]].explode("domains")
dom_df = dom_df.dropna()

from collections import Counter

domain_stats = {}

for dom, g in dom_df.groupby("domains"):
    cnt = Counter(g["label"])
    total = sum(cnt.values())
    best_label, best_freq = cnt.most_common(1)[0]
    purity = best_freq / total
    if total >= 30 and purity >= 0.9:
        domain_stats[dom] = (best_label, purity, total)

len(domain_stats)

13

In [38]:
def url_digit_ratio(url):
    digits = sum(c.isdigit() for c in url)
    return digits / max(len(url), 1)

df_dev["url_digit_ratio"] = df_dev["urls"].apply(
    lambda urls: max([url_digit_ratio(u) for u in urls], default=0)
)

In [30]:
def url_digit_ratio(url):
    digits = sum(c.isdigit() for c in url)
    return digits / max(len(url), 1)

df_dev["url_digit_ratio"] = df_dev["urls"].apply(
    lambda urls: max([url_digit_ratio(u) for u in urls], default=0)
)

In [31]:
df_dev.groupby("label")["url_digit_ratio"].describe()

         count      mean       std  min  25%  50%  75%       max
label
0      23542.0  0.047219  0.099572  0.0  0.0  0.0  0.0  0.555556
1      10588.0  0.025982  0.077193  0.0  0.0  0.0  0.0  0.376623
2      11161.0  0.038392  0.080633  0.0  0.0  0.0  0.0  0.415385
3       9977.0  0.030954  0.084311  0.0  0.0  0.0  0.0  0.384615
4       8574.0  0.028776  0.078755  0.0  0.0  0.0  0.0  0.325397
5      13053.0  0.025503  0.076541  0.0  0.0  0.0  0.0  0.376623
6       3102.0  0.013283  0.055720  0.0  0.0  0.0  0.0  0.317568

In [32]:
def clean_urls_light(text):
    return re.sub(
        r"https?://[^\s\"\'<>]{60,}",
        " URL_LONG ",
        text
    )

df_dev["article_clean"] = df_dev["article"].apply(clean_urls_light)
df_eval["article_clean"] = df_eval["article"].apply(clean_urls_light)

In [33]:
TAG_REGEX = re.compile(r"<\s*([a-zA-Z0-9]+)")

def extract_tags(text):
    return TAG_REGEX.findall(text.lower())

df_dev["tags"] = df_dev["article"].apply(extract_tags)

In [34]:
tag_df = df_dev[["label", "tags"]].explode("tags")
tag_df = tag_df.dropna()

tag_stats = {}

for tag, g in tag_df.groupby("tags"):
    cnt = Counter(g["label"])
    total = sum(cnt.values())
    best_label, best_freq = cnt.most_common(1)[0]
    purity = best_freq / total
    if total >= 50 and purity >= 0.9:
        tag_stats[tag] = (best_label, purity, total)

tag_stats

{'em': (2, 0.9384615384615385, 65),
 'font': (2, 0.9285714285714286, 84),
 'h4': (2, 1.0, 628),
 'strong': (2, 1.0, 135)}

In [39]:
# ============================
# ANALISI URL + META TAG HTML
# Dataset: ../data/raw/development.csv
# ============================

import pandas as pd
import re
from collections import Counter, defaultdict

# ----------------------------
# LOAD DATA
# ----------------------------
PATH = "../data/raw/development.csv"

df = pd.read_csv(PATH)
df["article"] = df["article"].fillna("")
df["label"] = df["label"].astype(int)

print("Dataset shape:", df.shape)
print("Labels:", sorted(df["label"].unique()))

# ----------------------------
# REGEX DEFINITIONS
# ----------------------------
URL_REGEX = re.compile(
	r'https?://[^\s"<>\]]+',
	flags=re.IGNORECASE
)

HTML_TAG_REGEX = re.compile(
	r'<\s*([a-zA-Z0-9]+)(\s+[^>]*)?>',
	flags=re.IGNORECASE
)

# ----------------------------
# URL FEATURE EXTRACTION
# ----------------------------
def extract_url_features(text):
	urls = URL_REGEX.findall(text)

	n_urls = len(urls)
	n_http = sum(u.lower().startswith("http://") for u in urls)
	n_https = sum(u.lower().startswith("https://") for u in urls)

	n_digits = sum(len(re.findall(r'\d', u)) for u in urls)
	avg_len = sum(len(u) for u in urls) / n_urls if n_urls > 0 else 0

	return pd.Series({
		"url_count": n_urls,
		"http_count": n_http,
		"https_count": n_https,
		"url_digits": n_digits,
		"url_avg_len": avg_len
	})

url_feats = df["article"].apply(extract_url_features)
df_url = pd.concat([df[["label"]], url_feats], axis=1)

print("\n--- URL FEATURES (sample) ---")
print(df_url.head())

# ----------------------------
# URL STATS PER LABEL
# ----------------------------
url_stats_by_label = (
	df_url
	.groupby("label")
	.agg(["mean", "std", "median"])
)

print("\n--- URL STATS BY LABEL ---")
print(url_stats_by_label)

# ----------------------------
# HTML TAG EXTRACTION
# ----------------------------
def extract_html_tags(text):
	return [m.group(1).lower() for m in HTML_TAG_REGEX.finditer(text)]

tag_counts_by_label = defaultdict(Counter)

for label, text in zip(df["label"], df["article"]):
	tags = extract_html_tags(text)
	tag_counts_by_label[label].update(tags)

tag_df = (
	pd.DataFrame(tag_counts_by_label)
	.fillna(0)
	.T
)

label_counts = df["label"].value_counts().sort_index()
tag_df_norm = tag_df.div(label_counts, axis=0)

print("\n--- HTML TAG DISTRIBUTION (normalized, sample) ---")
print(tag_df_norm.iloc[:, :10].head())

# ----------------------------
# TOP TAGS PER LABEL
# ----------------------------
TOP_K = 15

for label in sorted(tag_df_norm.index):
	print(f"\n=== TOP HTML TAGS | LABEL {label} ===")
	print(
		tag_df_norm
		.loc[label]
		.sort_values(ascending=False)
		.head(TOP_K)
	)

# ----------------------------
# OPTIONAL: FEATURE MATRICES
# ----------------------------
# Normalized numeric features (ready to join)
html_features = tag_df_norm.add_prefix("html_tag_")

# Binary presence features
html_features_binary = (tag_df > 0).astype(int).add_prefix("html_tag_bin_")

print("\nHTML feature matrices ready:")
print(" - html_features (normalized)")
print(" - html_features_binary (binary)")

# ----------------------------
# SUMMARY
# ----------------------------
print("\nDONE.")
print("Extracted:")
print("- URL structural features (http/https, digits, length)")
print("- HTML meta-tag distributions (no hardcoding)")
print("- Label-conditional statistics")

Dataset shape: (79997, 7)
Labels: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

--- URL FEATURES (sample) ---
   label  url_count  http_count  https_count  url_digits  url_avg_len
0      5        0.0         0.0          0.0         0.0          0.0
1      0        0.0         0.0          0.0         0.0          0.0
2      0        0.0         0.0          0.0         0.0          0.0
3      0        0.0         0.0          0.0         0.0          0.0
4      0        2.0         2.0          0.0        34.0        108.5

--- URL STATS BY LABEL ---
      url_count                  http_count                  https_count  \
           mean       std median       mean       std median        mean
label
0      0.448602  1.220120    0.0   0.448602  1.220120    0.0    0.000000
1      0.342180  1.023816    0.0   0.342180  1.023816    0.0    0.000000
2      1.218170  3.134639    0.0   1.216647  3.133501    0.0    0.001523
3      0.395109  2.026352    0.0   0.395109  2.026352    0.0    0.000000
4      0.252508  0.747508    0.0   0.252508  0.747508    0.0    0.000000
5      0.438980  1.859834    0.0   0.438980  1.859834    0.0    0.000000
6      0.153449  0.804886    0.0   0.153449  0.804886    0.0    0.000000

                       url_digits                   url_avg_len             \
            std median       mean        std median        mean        std
label
0      0.000000    0.0   8.024127  17.821143    0.0   22.586295  47.988493
1      0.000000    0.0   3.285417  11.165065    0.0   11.519141  30.479371
2      0.057559    0.0   6.949019  15.973875    0.0   19.436864  41.729106
3      0.000000    0.0   5.247068  14.908522    0.0   14.230563  39.431833
4      0.000000    0.0   5.387567  14.788698    0.0   15.509421  42.500304
5      0.000000    0.0   2.780204  10.419505    0.0    7.320493  19.673224
6      0.000000    0.0   2.264346   9.642284    0.0    6.528208  27.171420


      median
label
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
6        0.0

--- HTML TAG DISTRIBUTION (normalized, sample) ---
          a         p       img       div      font      nobr         i  \
0  0.218036  0.179891  0.230482  0.011724  0.000000  0.000000  0.000085
1  0.161881  0.085191  0.180015  0.019928  0.000283  0.000000  0.000094
2  0.593047  0.557746  0.623869  0.088702  0.006989  0.000090  0.003226
3  0.182921  0.120477  0.211988  0.015636  0.000100  0.000100  0.004711
4  0.125379  0.106368  0.127129  0.001866  0.000117  0.000117  0.000000

         br        em       hr
0  0.165109  0.000042  0.00017
1  0.040045  0.000000  0.00000
2  0.059941  0.005465  0.00000
3  0.107146  0.000100  0.00000
4  0.118614  0.000233  0.00000

=== TOP HTML TAGS | LABEL 0 ===
img      0.230482
a        0.218036
p        0.179891
br       0.165109
div      0.011724
td       0.000680
tr       0.000340
table    0.000170
span     0.000170
hr       0.000170
i        0.000085
em       0.000042
font     0.000000
nobr     0.000000
b        0.000000
Name: 0, dtype: float64

=== TOP HTML TAGS | LABEL 1 ===
img      0.180015
a        0.161881
p        0.085191
br       0.040045
div      0.019928
meta     0.002267
b        0.000283
font     0.000283
title    0.000094
i        0.000094
nobr     0.000000
em       0.000000
tr       0.000000
td       0.000000
table    0.000000
Name: 1, dtype: float64

=== TOP HTML TAGS | LABEL 2 ===
img       0.623869
a         0.593047
p         0.557746
div       0.088702
br        0.059941
h4        0.056267
b         0.012992
strong    0.012096
font      0.006989
em        0.005465
cite      0.004121
i         0.003226
strike    0.000179
small     0.000179
abbr      0.000179
Name: 2, dtype: float64

=== TOP HTML TAGS | LABEL 3 ===
img      0.211988
a        0.182921
p        0.120477
br       0.107146
div      0.015636
b        0.006014
i        0.004711
nobr     0.000100
font     0.000100
em       0.000100
table    0.000000
hr       0.000000
tr       0.000000
td       0.000000
span     0.000000
Name: 3, dtype: float64

=== TOP HTML TAGS | LABEL 4 ===
img      0.127129
a        0.125379
br       0.118614
p        0.106368
div      0.001866
em       0.000233
nobr     0.000117
font     0.000117
i        0.000000
hr       0.000000
table    0.000000
tr       0.000000
td       0.000000
span     0.000000
b        0.000000
Name: 4, dtype: float64

=== TOP HTML TAGS | LABEL 5 ===
img      0.237340
a        0.201486
div      0.050486
p        0.042366
i        0.000383
font     0.000077
nobr     0.000077
br       0.000000
em       0.000000
hr       0.000000
table    0.000000
tr       0.000000
td       0.000000
span     0.000000
b        0.000000
Name: 5, dtype: float64

=== TOP HTML TAGS | LABEL 6 ===
img      0.078337
a        0.075113
br       0.049323
p        0.048356
div      0.005803
font     0.000000
nobr     0.000000
i        0.000000
em       0.000000
hr       0.000000
table    0.000000
tr       0.000000
td       0.000000
span     0.000000
b        0.000000
Name: 6, dtype: float64

HTML feature matrices ready:
 - html_features (normalized)
 - html_features_binary (binary)

DONE.
Extracted:
- URL structural features (http/https, digits, length)
- HTML meta-tag distributions (no hardcoding)
- Label-conditional statistics

In [40]:
# ============================
# ANALISI PAROLE CON MAIUSCOLO
# Dataset: ../data/raw/development.csv
# ============================

import pandas as pd
import re
from collections import defaultdict, Counter

# ----------------------------
# LOAD DATA
# ----------------------------
PATH = "../data/raw/development.csv"

df = pd.read_csv(PATH)
df["article"] = df["article"].fillna("")
df["label"] = df["label"].astype(int)

print("Dataset shape:", df.shape)
print("Labels:", sorted(df["label"].unique()))

# ----------------------------
# REGEX DEFINITIONS
# ----------------------------

# Parole tipo: iPhone, Google, HTTPServer, AIModel
CAPITALIZED_WORD_REGEX = re.compile(
	r'\b[A-Z][a-zA-Z0-9]{2,}\b'
)

# Parole tipo: HTTP, API, JSON, GPU
ALL_CAPS_WORD_REGEX = re.compile(
	r'\b[A-Z]{2,}\b'
)

# ----------------------------
# FEATURE EXTRACTION
# ----------------------------
def extract_caps_features(text):
	capitalized = CAPITALIZED_WORD_REGEX.findall(text)
	all_caps = ALL_CAPS_WORD_REGEX.findall(text)

	return pd.Series({
		"capitalized_count": len(capitalized),
		"all_caps_count": len(all_caps),
		"unique_capitalized": len(set(capitalized)),
		"unique_all_caps": len(set(all_caps)),
	})

caps_feats = df["article"].apply(extract_caps_features)
df_caps = pd.concat([df[["label"]], caps_feats], axis=1)

print("\n--- CAPS FEATURES (sample) ---")
print(df_caps.head())

# ----------------------------
# STATS PER LABEL
# ----------------------------
caps_stats_by_label = (
	df_caps
	.groupby("label")
	.agg(["mean", "std", "median"])
)

print("\n--- CAPS STATS BY LABEL ---")
print(caps_stats_by_label)

# ----------------------------
# VOCABOLARIO CAPS PER LABEL
# ----------------------------
caps_vocab_by_label = defaultdict(Counter)

for label, text in zip(df["label"], df["article"]):
	caps_vocab_by_label[label].update(
		CAPITALIZED_WORD_REGEX.findall(text)
	)
	caps_vocab_by_label[label].update(
		ALL_CAPS_WORD_REGEX.findall(text)
	)

# ----------------------------
# TOP CAPS WORDS PER LABEL
# ----------------------------
TOP_K = 20

for label in sorted(caps_vocab_by_label.keys()):
	print(f"\n=== TOP CAPS WORDS | LABEL {label} ===")
	for word, cnt in caps_vocab_by_label[label].most_common(TOP_K):
		print(f"{word:20s} {cnt}")

# ----------------------------
# PRESENZA CAPS COME TRIGGER
# ----------------------------
df_caps["has_caps"] = (
	(df_caps["capitalized_count"] > 0) |
	(df_caps["all_caps_count"] > 0)
).astype(int)

caps_presence_by_label = (
	df_caps
	.groupby("label")["has_caps"]
	.mean()
)

print("\n--- P(has_caps | label) ---")
print(caps_presence_by_label)

# ----------------------------
# SUMMARY
# ----------------------------
print("\nDONE.")
print("Extracted:")
print("- capitalized words (CamelCase / ProperCase)")
print("- ALL CAPS tokens (API, HTTP, GPU, …)")
print("- label-conditional statistics")
print("- caps presence as deterministic trigger")

Dataset shape: (79997, 7)
Labels: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

--- CAPS FEATURES (sample) ---
   label  capitalized_count  all_caps_count  unique_capitalized  \
0      5                  8               2                   8
1      0                  6               0                   6
2      0                  4               0                   4
3      0                  1               0                   1
4      0                 12               1                  11

   unique_all_caps
0                2
1                0
2                0
3                0
4                1

--- CAPS STATS BY LABEL ---
      capitalized_count                   all_caps_count                   \
                   mean        std median           mean       std median
label
0              8.343981   7.406465    6.0       1.026761  1.191654    1.0
1              5.445977   4.857603    5.0       0.884209  1.369286    0.0
2              9.173192  14.470456    5.0       1.153929  2.516924    0.0
3              8.067255   7.087775    6.0       0.869400  1.157453    1.0
4              9.530441   6.747375    8.0       0.921390  1.157644    1.0
5              5.294338   3.697900    5.0       0.629510  0.854327    0.0
6              4.804642   4.274280    4.0       0.804320  1.029432    1.0

      unique_capitalized                  unique_all_caps
                    mean       std median            mean       std median
label
0               7.204783  5.363146    6.0        0.848101  0.909778    1.0
1               5.033623  3.963444    4.0        0.801757  1.134852    0.0
2               6.778962  7.443417    5.0        0.897859  1.408167    0.0
3               7.172898  5.225707    6.0        0.763656  0.983561    1.0
4               8.542221  4.839476    8.0        0.793679  0.942288    1.0
5               5.088026  3.480450    5.0        0.615414  0.812076    0.0
6               4.534172  3.627437    4.0        0.750161  0.904925    1.0

=== TOP CAPS WORDS | LABEL 0 ===
AFP                  8184
AP                   6165
The                  5059
Reuters              4960
President            2582
Wednesday            2068
Thursday             2042
Tuesday              1999
Monday               1993
Iraq                 1986
Friday               1980
Photo                1614
US                   1593
Sunday               1514
Minister             1490
Bush                 1417
Saturday             1365
United               1277
British              1218
File                 1181

=== TOP CAPS WORDS | LABEL 1 ===
Reuters              3078
NEW                  2152
YORK                 2130
The                  2035
Inc                  1345
Corp                 929
Tuesday              825
Thursday             812
Monday               792
US                   771
HREF                 768
Wednesday            750
Friday               727
WASHINGTON           594
LONDON               420
Street               414
Wall                 403
FullQuote            384
New                  375
Group                334

=== TOP CAPS WORDS | LABEL 2 ===
News                 4536
Computerworld        4241
The                  3856
Microsoft            1276
ArticleBody          1024
AP                   989
Reuters              850
Internet             845
Web                  801
AFP                  796
Inc                  772
IBM                  678
Google               603
NASA                 590
Apple                586
Tuesday              541
Corp                 539
Thursday             506
Windows              500
Wednesday            497

=== TOP CAPS WORDS | LABEL 3 ===
The                  2708
AP                   1892
Reuters              1858
US                   761
LOS                  738
ANGELES              736
New                  662
Tuesday              653
Photo                611
Thursday             594
Monday               586
Wednesday            585
Friday               580
NEW                  544
Hollywood            516
YORK                 516
Sunday               503
York                 495
President            462
American             384

=== TOP CAPS WORDS | LABEL 4 ===
AP                   2436
The                  1970
New                  884
Sunday               844
Reuters              818
Photo                789
Saturday             726
Friday               637
Thursday             614
Wednesday            613
Tuesday              563
NFL                  552
NBA                  544
York                 541
Cup                  535
Monday               508
League               450
World                438
NEW                  416
Open                 394

=== TOP CAPS WORDS | LABEL 5 ===
Reuters              2945
The                  2022
WASHINGTON           1150
Iraq                 994
President            968
US                   847
Thursday             755
Wednesday            748
Tuesday              743
Monday               736
Bush                 688
Friday               678
BAGHDAD              670
Sunday               533
United               466
Saturday             456
CNN                  450
NEW                  450
Iraqi                445
YORK                 406

=== TOP CAPS WORDS | LABEL 6 ===
Reuters              807
The                  567
NEW                  426
YORK                 404
WASHINGTON           354
Health               332
AP                   307
HealthDay            252
AIDS                 250
Tuesday              191
Wednesday            178
Monday               172
Thursday             162
HIV                  160
Friday               151
AFP                  142
US                   137
Food                 122
CHICAGO              118
New                  117

--- P(has_caps | label) ---
label
0    0.990273
1    0.899603
2    0.983156
3    0.990979
4    0.996968
5    0.910519
6    0.971631
Name: has_caps, dtype: float64

DONE.
Extracted:
- capitalized words (CamelCase / ProperCase)
- ALL CAPS tokens (API, HTTP, GPU, …)
- label-conditional statistics
- caps presence as deterministic trigger

In [41]:
COUNTRIES = [
	"Afghanistan","Albania","Algeria","Andorra","Angola","Antigua","Argentina",
	"Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh",
	"Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia",
	"Bosnia","Botswana","Brazil","Brunei","Bulgaria","Burkina","Burundi",
	"Cambodia","Cameroon","Canada","Chad","Chile","China","Colombia","Comoros",
	"Congo","Costa Rica","Croatia","Cuba","Cyprus","Czech","Denmark","Djibouti",
	"Dominica","Ecuador","Egypt","El Salvador","Estonia","Ethiopia","Fiji",
	"Finland","France","Gabon","Gambia","Georgia","Germany","Ghana","Greece",
	"Grenada","Guatemala","Guinea","Guyana","Haiti","Honduras","Hungary",
	"Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy",
	"Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kuwait","Latvia","Lebanon",
	"Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg",
	"Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Mauritania",
	"Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro","Morocco",
	"Mozambique","Myanmar","Namibia","Nepal","Netherlands","New Zealand",
	"Nicaragua","Niger","Nigeria","Norway","Oman","Pakistan","Panama","Paraguay",
	"Peru","Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda",
	"Saudi Arabia","Senegal","Serbia","Singapore","Slovakia","Slovenia",
	"Somalia","South Africa","Spain","Sri Lanka","Sudan","Suriname","Sweden",
	"Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Togo",
	"Tonga","Tunisia","Turkey","Turkmenistan","Uganda","Ukraine",
	"United Arab Emirates","United Kingdom","United States","Uruguay",
	"Uzbekistan","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"
]
import re

COUNTRY_REGEX = re.compile(
	r'\b(?:' + '|'.join(re.escape(c) for c in COUNTRIES) + r')\b',
	flags=re.IGNORECASE
)
import pandas as pd

# ----------------------------
# LOAD DATA
# ----------------------------
PATH = "../data/raw/development.csv"
df = pd.read_csv(PATH)
df["article"] = df["article"].fillna("")
df["label"] = df["label"].astype(int)

# ----------------------------
# FEATURE: COUNTRY PRESENCE
# ----------------------------
def has_country(text):
	return int(bool(COUNTRY_REGEX.search(text)))

df["has_country"] = df["article"].apply(has_country)

# ----------------------------
# P(has_country | label)
# ----------------------------
p_country_given_label = (
	df.groupby("label")["has_country"]
	.mean()
)

print("\n--- P(has_country | label) ---")
print(p_country_given_label)

# ----------------------------
# P(label | has_country = 1)
# ----------------------------
label_dist_if_country = (
	df[df["has_country"] == 1]["label"]
	.value_counts(normalize=True)
	.sort_index()
)

print("\n--- P(label | has_country = 1) ---")
print(label_dist_if_country)

# ----------------------------
# SUPPORT
# ----------------------------
support = df["has_country"].mean()
print("\nSupport P(has_country):", support)

--- P(has_country | label) ---
label
0    0.413771
1    0.111447
2    0.091210
3    0.180315
4    0.149405
5    0.265303
6    0.116699
Name: has_country, dtype: float64

--- P(label | has_country = 1) ---
label
0    0.516928
1    0.062619
2    0.054023
3    0.095468
4    0.067979
5    0.183772
6    0.019210
Name: proportion, dtype: float64

Support P(has_country): 0.2355588334562546